---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  deploy_to_forge:
    enabled: false
  branches:
  - release
  user: puppet
  secure: ''
  includes:
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=debian_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_deb]'
    - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
    - bundle exec rake 'litmus:install_agent[puppet5]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=debian_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_deb]'
    - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
    - bundle exec rake 'litmus:install_agent[puppet6]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=el6_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el6]'
    - bundle exec rake 'litmus:install_agent[puppet5]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=el6_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el6]'
    - bundle exec rake 'litmus:install_agent[puppet6]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=el7_puppet5
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el7]'
    - bundle exec rake 'litmus:install_agent[puppet5]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  - bundler_args: 
    dist: trusty
    env: PLATFORMS=el7_puppet6
    rvm: 2.5.3
    before_script:
    - bundle exec rake 'litmus:provision_list[travis_el7]'
    - bundle exec rake 'litmus:install_agent[puppet6]'
    - bundle exec rake litmus:install_module
    script:
    - bundle exec rake litmus:acceptance:parallel
    services: docker
    sudo: required
    stage: acceptance
  simplecov: true
  notifications:
    slack:
      secure: >-
        mcqiGIDFoMEYXxvjyB//JeQ9P4pF74bJkqAvstX0Po5qZjUpLs45bB05yZJlfE2mU+eJ2JNlcOajfy4b7FeaoIWI8V3kAqqOrWDOt9/6myAebmWtWfzjE6SAHkpWkT09LFDoYKalNAtb/prt8Em8hlc3Id20Hbsab5BYy/5gixArU5rDv4GJcXQalf/cmeY9vJk1N4W1dDNjUKkBPZ28cwph5DQM8tdGPfrag0L0dZJ6E1NJPXS8nL3fUH3T3nqIp+UKLbefKVT28q2DNkYBJ0KY1Cbh9w16/z2XGkGbqNzEfqJPAzy0OVd5wm0R428p8S/3ch5RayiUmLDF9G5j7pSt3Fnp9mrcb4gO2FFWNUBaq/lF4/R3/r7gXo0i99DeHvERYLWb7EaQoDz7M25d9U2RxwkOdb15HOVY8AOzKT7NqqCxzz4drY/I8WftQ0zUALOLYBVJhMFpfpZzeG14ziL5nuJQVz8qAF2KqcuIeqCxZ8j4ggnczHO9WjMi3uL5fAf6LnGl9g+3jKrFF6G4r+lAKJTzh0WXCcM7bkREXhy0lRiSvP5rFWBugtEm+YX7E/p5dbjtwiQ9d9KOJQ8OOk+tUACDZKVbXyizGXvsR8aa25Yl6y0pAewVwmzlCO/VZhLu8o83cP0wOiUVUSbEjyRj3Vni5FxIaj2Sr5slyaQ=
".yardopts":
  optional:
  - "--output-dir docs/"
appveyor.yml:
  simplecov: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
      git: https://github.com/skywinder/github-changelog-generator
      ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
